"""empty message

Revision ID: c03b8054937a
Revises: fd8e884c6f54
Create Date: 2023-10-22 11:07:47.243918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03b8054937a'
down_revision = 'fd8e884c6f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languageskills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('percentage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_languageskills'))
    )
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('coverimage', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('filters', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios'))
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services'))
    )
    with op.batch_alter_table('techskills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('percentage', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('techskills', schema=None) as batch_op:
        batch_op.drop_column('percentage')
        batch_op.drop_column('title')

    op.drop_table('services')
    op.drop_table('portfolios')
    op.drop_table('languageskills')
    # ### end Alembic commands ###
